# Set up notification options
notifications:
  email:
    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# specify language
language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

# Uncomment for GDAL intall if needed for testing
before_install:
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get -y update
    - sudo apt-get -y install python-gdal libgdal-dev libgdal1-dev libgdal-doc gdal-bin
## command to install dependencies
install: 'pip install -r requirements.txt'

## Script to run
script: py.test

branches:
  ## whitelist
  only:
    - master
    - staging

# blacklist
  except:
    - /^.*test.*$/
